name: Web API Deploy Pipeline
# 「cicd-section/api/」配下に変更があった時のみ
on:
  push:
    paths:
      - ".github/workflows/**"
      - "cicd-section/api/**"

env:
  AWS_REGION: ap-northeast-1
  ECS_CLUSTER: my-app-cluster
  ECS_SERVICE: my-app-api-service
  ECR_REPOSITORY: my-app-api
  ECS_TASK_DEFINITION_API: cicd-section/.aws/task-def-api.json

permissions:
  id-token: write # ID tokenを要求
  contents: read # checkoutのため

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    # 作業ディレクトリの変更
    defaults:
      run:
        working-directory: cicd-section/api
    steps:
      - uses: actions/checkout@v4

      - name: Run Test and Build an Image
        run: docker image build -t temp_api_image:latest .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with: # parameter
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push the image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }} # login-ecrの出力結果
        run: |
          docker image tag temp_api_image:latest $ECR_REGISTORY/$ECR_REPOSITORY:${{ github.sha }}
          docker image push $ECR_REGISTORY/$ECR_REPOSITORY:${{ github.sha }}
